In [23]:
import os 

def load_files(all_file_or_not, n_files = 0):
    file_paths = []
    main_dir = '../latent_diffusion/data/03001627_sdfs/'

    if all_file_or_not: # loading all files
        n_files = 0
        for sub_dir in os.scandir(main_dir):
            if sub_dir.is_dir():
                for file in os.listdir(main_dir + sub_dir.name):
                    file_paths.append(main_dir + sub_dir.name + '/' + file) if file == "sdf_samples.npz" else None
            n_files += 1
            
    else: # loading specific # of files
        for sub_dir in os.scandir(main_dir):
            if sub_dir.is_dir():
                for file in os.listdir(main_dir + sub_dir.name):
                    file_paths.append(main_dir + sub_dir.name + '/' + file) if file == "sdf_samples.npz" else None
            if len(file_paths) == n_files:
                break
    
    print(f'total # of files: {n_files}')
    return file_paths

# path example: latent_diffusion/latent_diffusion/data/03001627_sdfs/1006be65e7bc937e9141f9b58470d646

In [34]:
# load all filepaths
filepaths = load_files(True)

# load shape indices used for diffusion
diffusion_model_dt = '10062022_011812' # used 6278 trainign shapes
diffusion_log_filename = f'../latent_diffusion/diffusion logs & models/{diffusion_model_dt}/{diffusion_model_dt}.log'

with open(diffusion_log_filename) as f:
    f = f.readlines()

for idx, line in enumerate(f):
    if "Shape indices" in line:
        shape_indices = line.split('=')[1].strip().strip('[').strip(']')

shape_indices = shape_indices.split(', ')
shape_indices = [int(shape_index) for shape_index in shape_indices]

# get shapenames matching to the shape indices 
shape_names = []
for shape_index in shape_indices:
    shape_names.append(filepaths[shape_index].split('/')[4])

# check if all shapenames are retrieved
print(len(shape_names))

# hard coding the dictionary keys according to our sdf files architecture
dictionary = {"data": {"03001627_sdfs": shape_names}} 

import json
json_object = json.dumps(dictionary, indent=2)
 
with open("./examples/chairs/chairs_train.json", "w") as outfile:
    outfile.write(json_object)

total # of files: 6778
6278


In [44]:
import numpy as np
# path example: latent_diffusion/latent_diffusion/data/03001627_sdfs/1006be65e7bc937e9141f9b58470d646
filename = "../latent_diffusion/data/03001627_sdfs/1006be65e7bc937e9141f9b58470d646"
pos_npz = np.load(os.path.join(filename, 'pos_sdf_samples.npz'))
neg_npz = np.load(os.path.join(filename, 'neg_sdf_samples.npz'))
    
    # if subsample is None:
    #     return npz
    
    # concatenate xyz + sdf horizontally
pos_points = pos_npz['points']
print(pos_points)

pos_sdfs = np.resize(pos_npz['sdf'], (len(pos_npz['sdf']), 1))
print(pos_sdfs)
pos_tensor = np.concatenate((pos_points, pos_sdfs), axis = 1)
print(pos_tensor)

[[ 0.00284584  0.3508967   0.32118544]
 [ 0.3907591   0.4502787   0.39157248]
 [ 0.05056688  0.06562302  0.267699  ]
 ...
 [ 0.96285063  0.2036773   0.00703624]
 [ 0.28542417  0.7473609  -0.26989472]
 [ 0.6533466  -0.15837108 -0.5224776 ]]
[[0.00147297]
 [0.00215678]
 [0.00245939]
 ...
 [0.53866714]
 [0.7109576 ]
 [0.26529077]]
[[ 0.00284584  0.3508967   0.32118544  0.00147297]
 [ 0.3907591   0.4502787   0.39157248  0.00215678]
 [ 0.05056688  0.06562302  0.267699    0.00245939]
 ...
 [ 0.96285063  0.2036773   0.00703624  0.53866714]
 [ 0.28542417  0.7473609  -0.26989472  0.7109576 ]
 [ 0.6533466  -0.15837108 -0.5224776   0.26529077]]
